services:
  - type: web
    name: damla-crm
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: sh -c "python manage.py migrate && python manage.py init_default_users && gunicorn damla_crm.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: DATABASE_URL
        fromDatabase:
          name: damla-crm-db
          property: connectionString
    autoDeploy: true
    healthCheckPath: /
databases:
  - name: damla-crm-db
    plan: free
